from __future__ import annotations

from app.config.settings import AppSettings

TEXTS = {
    "en": {"title": "Deleter", "scan": "Scan", "choose": "Choose folder", "stop": "Stop", "pause": "Pause", "resume": "Resume", "simulate": "Simulation mode", "threshold": "Minimum file size", "custom_size": "Custom value…", "programs": "Programs", "files": "Files", "system_scan": "System scan", "protected": "LOCKED", "review": "Review", "protection": "Protection", "version": "Version", "publisher": "Publisher", "install_location": "Install location", "uninstall": "Uninstall command", "select_all": "Select all visible", "clear": "Clear selection", "review_selection": "Review selection", "deinstall": "Mark programs for uninstall", "recycle": "Move selected to Recycle Bin", "details": "Show information", "install_date": "Install date", "used_space": "Used space", "uninstall_method": "Uninstall method", "access": "Access", "reason": "Cleanup reason", "results": "Results", "status_ready": "Ready", "status_scanning": "Scanning…", "status_done": "Scan complete: {count} files found.", "status_stopped": "Scan stopped.", "path": "Path", "name": "Name", "size": "Size", "modified": "Modified", "risk": "Risk", "delete": "Preview cleanup", "no_results": "No matching files.", "selected": "{count} selected, {size}.", "locked_count": "{count} elements are locked and cannot be deleted.", "preview": "Simulation only: no files will be deleted.", "errors": "Scan warnings: {count}", "access_denied": "Access denied (Windows error 5): {path}", "live_status": "Scanned {scanned}; found {matched}; skipped {skipped}; locked {protected}; errors {errors}; current area: {path}"},
    "de": {"title": "Deleter", "scan": "Scannen", "choose": "Ordner auswählen", "stop": "Stoppen", "pause": "Pausieren", "resume": "Fortsetzen", "simulate": "Simulationsmodus", "threshold": "Mindestgröße", "custom_size": "Benutzerdefinierter Wert…", "programs": "Programme", "files": "Dateien", "system_scan": "Systemanalyse", "protected": "GESPERRT", "review": "Prüfung erforderlich", "protection": "Schutz", "version": "Version", "publisher": "Herausgeber", "install_location": "Installationspfad", "uninstall": "Deinstallationsbefehl", "results": "Ergebnisse", "status_ready": "Bereit", "status_scanning": "Scan läuft…", "status_done": "Scan abgeschlossen: {count} Dateien gefunden.", "status_stopped": "Scan angehalten.", "path": "Pfad", "name": "Name", "size": "Größe", "modified": "Geändert", "risk": "Risiko", "delete": "Bereinigung prüfen", "no_results": "Keine passenden Dateien.", "selected": "{count} ausgewählt, {size}.", "locked_count": "{count} Elemente sind gesperrt und können nicht gelöscht werden.", "preview": "Nur Simulation: Es werden keine Dateien gelöscht.", "errors": "Scan-Warnungen: {count}", "live_status": "Analysiert: {scanned}; gefunden: {matched}; übersprungen: {skipped}; gesperrt: {protected}; Fehler: {errors}; aktueller Bereich: {path}"},
    "tr": {"title": "Deleter", "scan": "Tara", "choose": "Klasör seç", "stop": "Durdur", "pause": "Duraklat", "resume": "Devam et", "simulate": "Simülasyon modu", "threshold": "En düşük dosya boyutu", "custom_size": "Özel değer…", "programs": "Programlar", "files": "Dosyalar", "system_scan": "Sistem taraması", "protected": "KİLİTLİ", "review": "İncelenmeli", "protection": "Koruma", "version": "Sürüm", "publisher": "Yayıncı", "install_location": "Kurulum konumu", "uninstall": "Kaldırma komutu", "results": "Sonuçlar", "status_ready": "Hazır", "status_scanning": "Taranıyor…", "status_done": "Tarama tamamlandı: {count} dosya bulundu.", "status_stopped": "Tarama durduruldu.", "path": "Yol", "name": "Ad", "size": "Boyut", "modified": "Değiştirilme", "risk": "Risk", "delete": "Temizlemeyi önizle", "no_results": "Eşleşen dosya yok.", "selected": "{count} seçili, {size}.", "locked_count": "{count} öğe kilitli ve silinemez.", "preview": "Yalnızca simülasyon: dosya silinmeyecek.", "errors": "Tarama uyarıları: {count}", "live_status": "Taranan: {scanned}; bulunan: {matched}; atlanan: {skipped}; kilitli: {protected}; hatalar: {errors}; geçerli alan: {path}"},
}

TEXTS["de"].update({"select_all": "Alle sichtbaren auswählen", "clear": "Auswahl aufheben", "review_selection": "Auswahl prüfen", "deinstall": "Programme zur Deinstallation vormerken", "recycle": "Ausgewählte Elemente in den Papierkorb verschieben", "details": "Informationen anzeigen", "install_date": "Installationsdatum", "used_space": "Belegter Speicherplatz", "uninstall_method": "Deinstallationsmethode", "access": "Zugriff", "reason": "Bereinigungsgrund", "access_denied": "Zugriff verweigert (Windows-Fehler 5): {path}", "selection_status": "{count} ausgewählt, {size}; gesperrt: {locked}; kein Zugriff: {inaccessible}; erhöhtes Risiko: {risk}"})
TEXTS["tr"].update({"select_all": "Görünenlerin tümünü seç", "clear": "Seçimi temizle", "review_selection": "Seçimi incele", "deinstall": "Programları kaldırma için işaretle", "recycle": "Seçilenleri Geri Dönüşüm Kutusu'na taşı", "details": "Bilgileri göster", "install_date": "Kurulum tarihi", "used_space": "Kullanılan alan", "uninstall_method": "Kaldırma yöntemi", "access": "Erişim", "reason": "Temizleme nedeni", "access_denied": "Erişim reddedildi (Windows hatası 5): {path}", "selection_status": "{count} seçili, {size}; kilitli: {locked}; erişilemiyor: {inaccessible}; yüksek risk: {risk}"})
TEXTS["en"]["selection_status"] = "{count} selected, {size}; locked: {locked}; inaccessible: {inaccessible}; elevated risk: {risk}"
for language, values in {
    "de": {"cleanup": "Ausgewählte Elemente in den Papierkorb verschieben", "export_json": "Scan als JSON exportieren", "export_csv": "Scan als CSV exportieren", "confirm_cleanup": "Die ausgewählten Dateien werden nach einer letzten Sicherheitsprüfung in den Papierkorb verschoben. Fortfahren?", "cleanup_done": "Bereinigung abgeschlossen: {success} erfolgreich, {skipped} übersprungen.", "uninstall_done": "Deinstallation abgeschlossen: {success} erfolgreich, {failed} fehlgeschlagen.", "no_selection": "Keine Elemente ausgewählt."},
    "tr": {"cleanup": "Seçilenleri Geri Dönüşüm Kutusu'na taşı", "export_json": "Taramayı JSON olarak dışa aktar", "export_csv": "Taramayı CSV olarak dışa aktar", "confirm_cleanup": "Seçilen dosyalar son güvenlik kontrolünden sonra Geri Dönüşüm Kutusu'na taşınacak. Devam edilsin mi?", "cleanup_done": "Temizleme tamamlandı: {success} başarılı, {skipped} atlandı.", "uninstall_done": "Kaldırma tamamlandı: {success} başarılı, {failed} başarısız.", "no_selection": "Hiçbir öğe seçilmedi."},
}.items():
    TEXTS[language].update(values)
TEXTS["en"].update({"cleanup": "Move selected to Recycle Bin", "export_json": "Export scan as JSON", "export_csv": "Export scan as CSV", "confirm_cleanup": "Selected files will be moved to the Recycle Bin after a final safety check. Continue?", "cleanup_done": "Cleanup complete: {success} succeeded, {skipped} skipped.", "uninstall_done": "Uninstallation complete: {success} succeeded, {failed} failed.", "no_selection": "No items selected."})


class Translator:
    def __init__(self, settings: AppSettings) -> None:
        self.settings = settings

    @property
    def language(self) -> str:
        return self.settings.language if self.settings.language in TEXTS else "en"

    def text(self, key: str, **values: object) -> str:
        return TEXTS[self.language].get(key, TEXTS["en"].get(key, key)).format(**values)

